apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: view-embeddings-pvc
  labels:
    app: view-embeddings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.embeddings.storage.size }}
  storageClassName: {{ .Values.embeddings.storage.storageClass | default "" }}