apiVersion: v1
kind: Service
metadata:
  name: view-embeddings
  labels:
    app: view-embeddings
spec:
  type: {{ .Values.embeddings.service.type }}
  ports:
    - port: {{ .Values.embeddings.service.port }}
      targetPort: {{ .Values.embeddings.port }}
  selector:
    app: view-embeddings